@startuml classdiagram
    Titre -- Compte
    Utilisateur -- Compte
    BrokerBean -- Titre
    BrokerBean -- Utilisateur
    BrokerBean -- Compte
    TitreService -- BrokerBean
    TitreRessource -- TitreService
    UtilisateurService -- BrokerBean
    UtilisateurRessource -- UtilisateurService


    class Titre {
        String nomEntreprise
        String mnemonique
        Double cours 
        Integer variation
        Date dateCours
        void methods()
    }

    class Compte {
        Long id
        Long idUser
        Double solde
        List<Titre> titres
        void methods()
    }

    class Utilisateur {
        Long id
        String nom
        List<Compte> compte
        Compte compteActif
        void methods()
    }

    class BrokerBean {
        List<Utilisateur> utilisateurs
        List<Titre> titres
        
        + Utilisateur ajouterUtilisateur(Utilisateur aAjouter)
        + Utilisateur supprimerUtilisateur(Utilisateur aSupprimer)
        + Utilisateur debiter(Integer aDebiter, Utilisateur aCrediter)
        + Utilisateur crediter(Integer aCrediter, Utilisateur aDebiter)
        + Utilisateur ajouterCompte(Utilisateur aModifier)
        + Utilisateur supprimerSupprimer(Utilisateur aModifier)
        + Titre ajouterTitre(Titre aAjouter, Utilisateur aModifier)
        + Titre supprimerTitre(Titre aSupprimer, Utilisateur aModifier)

        + mAJListTitre(List<Titre> listAjour)
        + consulterTitre(String mnemonique)
        + rechercheMnemonique(String mnemonique)
    }

    Class TitreService {
        + ListTitre consulterTitre(String mnemonique)
        + List<Titre> rechercheMnemonique(String mnemonique)

        - JMS mAJListTitre()
    }

    class TitreRessource {
        GET consulterTitre()
        GET rechercheMnemonique()

    }
    note left: Endpoint REST

    Class UtilisateurService {
        + Utilisateur ajouterUtilisateur(data)
        + Utilisateur supprimerUtilisateur(data)
        + Titre acheterAction(data)
        + mettreVenteAction(data)

        - JMS transfererArgent(Double aTransferer)
        - JMS transfererTitre(Double aTransferer)
        - JMS recpetionnerTitre(Double aTransferer)
        - JMS receptionnerArgent(Double aTransferer)
    }

    class UtilisateurRessource {
        POST ajouterUtilisateur()
        DELETE supprimerUtilisateur()
        POST acheterAction()
        POST mettreVenteAction()
    }
    note right: Endpoint REST 

@enduml